# Generated by Django 5.1.5 on 2025-03-04 15:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_auto_20250303_2130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='planchoice',
            old_name='plan',
            new_name='plan_code',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='payment_provider_id',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='plan',
        ),
        migrations.AddField(
            model_name='subscription',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='subscription',
            name='external_subscription_id',
            field=models.CharField(default='', max_length=255, verbose_name='External subscription ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscription',
            name='plan_choice',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='client.planchoice'),
            preserve_default=False,
        ),
    ]
